/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_svgdoc_free(a: number): void;
export function svgdoc_new(): number;
export function svgdoc_get_group(a: number, b: number, c: number): number;
export function svgdoc_add_group(a: number, b: number, c: number, d: number): void;
export function svgdoc_get_circle(a: number, b: number, c: number): number;
export function svgdoc_add_circle(a: number, b: number, c: number, d: number): void;
export function svgdoc_edit_circle(a: number, b: number, c: number, d: number): void;
export function svgdoc_get_rectangle(a: number, b: number, c: number): number;
export function svgdoc_add_rectangle(a: number, b: number, c: number, d: number): void;
export function svgdoc_edit_rectangle(a: number, b: number, c: number, d: number): void;
export function svgdoc_get_path(a: number, b: number, c: number): number;
export function svgdoc_add_path(a: number, b: number, c: number, d: number): void;
export function svgdoc_edit_path(a: number, b: number, c: number, d: number): void;
export function svgdoc_edit_path_point_type(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function svgdoc_edit_path_point_pos(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function svgdoc_edit_path_point_handle1(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function svgdoc_edit_path_point_handle2(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function svgdoc_add_point_to_path(a: number, b: number, c: number, d: number, e: number): void;
export function svgdoc_move_object_to_group(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function svgdoc_move_object_to_root(a: number, b: number, c: number, d: number): void;
export function svgdoc_remove_object(a: number, b: number, c: number): void;
export function svgdoc_remove_path_point(a: number, b: number, c: number, d: number, e: number): void;
export function svgdoc_save(a: number, b: number): void;
export function svgdoc_merge(a: number, b: number, c: number): void;
export function svgdoc_children(a: number): number;
export function svgdoc_repr(a: number, b: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
